export const INCREASE_BASKET = "INCREASE_BASKET";
export const DECREASE_BASKET = "DECREASE_BASKET";
export const INCREASE_FAV = "INCREASE_FAV";
export const DECREASE_FAV = "DECREASE_FAV";


export const SET_SEARCH = "SET_SEARCH";
export const SET_PRICEFROM = "SET_PRICEFROM";
export const SET_PRICETO = "SET_PRICETO";
export const SET_CATEGORY = "SET_CATEGORY";


